export interface IEntidadesFornecedoresModel {
  id_Entidade: string,
  id_Fornecedor: string,
  nome: string,
  apelido: string,
  tipo_Pessoa: string,
  cpf_Cnpj: string,
  id_Banco: string,
  agencia: string,
  conta_Corrente: string,
  observacoes: string,
  ie: string,
  sexo: string,
  data_Abertura: string,
  img_Logo: string,
  file_Base64: string,
  user_Create: string,
  user_Alter: string,
  date_Create: string,
  date_Alter: string,
  ativo: boolean,
  ativoStr: string,
  date_Create_Str: string,
  date_Alter_Str: string
}