export interface IUsuariosAcessos {
  id_usuario_acesso: string,
	nome_usuario: string,
	nome_grupo: string,
	id_grupo?: string,
	usuario: string,
	is_adm: boolean,
  is_adm_str: string,
	is_locked: boolean,
	is_locked_str: string,
	ativo: boolean,
	ativo_str: string,
	sem_restricoes: boolean, 
	deslogar_automaticamente: boolean, 
	hora_minima_login: string,
	hora_maxima_login: string,
  dia_semana_inicial: number,
	dia_semana_final: number,
  user_create: string,
  user_alter: string,
  date_create: string,
  date_alter: string,
  data_connection: string,
  data_connection_str: string,
  date_create_str: string,
  date_alter_str: string
}