export interface IValoresPeriodosModel {
  id_Valor_Periodo?: string,
  id_Veiculo_Categoria: string,
  valor_Horas: number,
  periodo_Horas: number,
  tolerancia_Horas: number,
  valor_Excedente: number,
  perc_Desc_Min: number,
  perc_Desc_Max: number,
  nome_Categoria: string,
  perc_Desc_Max_Desc: string,
  perc_Desc_Min_Desc: string,
  valor_Horas_Desc: string,
  valor_Excedente_Desc: string,
  user_Create: string,
  user_Alter: string,
  date_Create: string,
  date_Create_Str: string,
  date_Alter: string,
  date_Alter_Str: string,
  ativo: boolean,
  ativoStr: string
}