export interface IVendasPagamentosModel {
  id_Venda_Pagamento: string,
  id_Venda: string,
  id_Forma_Pagamento: string,
  nome_FormaPagamento: string,
  observacao: string,
  valor_Pago_Str: string,
  valor_Pago: number,
  valor_Parcela_Str: string,
  valor_Pri_Parcela: number,
  valor_A_Vista: number,
  valor_Demais_Parcela: number,
  data_Vencimento_Str: string,
  data_Vencimento: string,
  data_Pagamento_Str: string,
  data_Pagamento: string,
  numero_Parcela: number,
  user_Create: string,
  user_Alter: string,
  date_Create: string,
  date_Create_Str: string,
  date_Alter: string,
  date_Alter_Str: string,
  ativo: boolean,
  ativoStr: string
}